extensions:
  health_check:
  pprof:
  zpages:

receivers:
  otlp:
    protocols:
      grpc:
      http:
  fluentforward:
    endpoint: 0.0.0.0:24224
  # TODO: use promtail receiver when it gets to upstream
  # promtail:
  #  config:
  #   positions:
  #     filename: /tmp/positions.yaml
  #     sync_period: 10s
  #   scrape_configs:
  #     - job_name: push
  #       loki_push_api:
  #         server:
  #           http_listen_port: 4318
  #                 # Data sources: traces, metrics, logs

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp]
    logs:
      receivers: [fluentforward]
      processors: [batch]
      exporters: [loki]
